name: Update submodule pointer (Computational-biology)

on:
  workflow_dispatch: {}           # 手动触发
  schedule:
    - cron: "0 */6 * * *"         # 可选：每 6 小时轮询一次（UTC）
  repository_dispatch:
    types: [compbio-updated]      # 可选：接收分仓库的“更新通知”触发

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update submodule to latest remote commit
        run: |
          # 跟踪 .gitmodules 里设置的 branch 拉取远端最新 commit
          git submodule update --init --remote submodules/computational-biology

          # 如果有变化，则创建提交；否则直接退出
          if ! git diff --quiet; then
            BR="chore/update-compbio-$(date +%Y%m%d%H%M%S)"
            git checkout -b "$BR"
            git add submodules/computational-biology
            NEW_REV=$(cd submodules/computational-biology && git rev-parse --short HEAD)
            git commit -m "chore: bump Computational-biology submodule to ${NEW_REV}"
          else
            echo "No submodule changes."
            exit 0
          fi

      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MIRROR_TOKEN }}   # 在总仓库的 Secrets 设置（见下文）
          commit-message: "chore: bump Computational-biology submodule"
          title: "chore: Update Computational-biology submodule"
          body: |
            This PR updates `submodules/computational-biology` to the latest commit on `main`.
            Auto-generated by CI.
          branch: "ci/update-compbio"
          base: "main"
